USE mysql;
GRANT ALL PRIVILEGES ON *.* TO 'yona'@'localhost' IDENTIFIED BY 'password' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'yona'@'127.0.0.1' IDENTIFIED BY 'password' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'yona'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;
create database yona DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_bin;
FLUSH PRIVILEGES;